export const GET_CHARACTERS_REQUEST = "GET_CHARACTERS_REQUEST";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const GET_CHARACTERS_FAILED = "GET_CHARACTERS_FAILED";

export const GET_PERS_REQUEST = "GET_PERS_REQUEST";
export const GET_PERS_SUCCESS = "GET_PERS_SUCCESS";
export const GET_PERS_FAILED = "GET_PERS_FAILED";
